
# Required
version: 2

# Build documentation in the docs/src directory with Sphinx (and
# ignore docs/analysis!)
sphinx:
   configuration: docs/src/conf.py

python:
   version: "3.8"
   install:
   - requirements: docs/requirements.txt