apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"gitlab-sa-1228-ns-admin"},"rules":[{"apiGroups":[""],"resources":["storageclasses","resourcequotas","persistentvolumes","limitranges","nodes","componentstatuses"],"verbs":["list","get","watch"]},{"apiGroups":[""],"resources":["serviceaccounts"],"verbs":["list","get","watch","create","update","patch","delete"]},{"apiGroups":["autoscaling"],"resources":["horizontalpodautoscalers"],"verbs":["list","get","watch"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["list","get","watch"]},{"apiGroups":["admissionregistration.k8s.io"],"resources":["mutatingwebhookconfigurations","validatingwebhookconfigurations"],"verbs":["list","get","watch"]},{"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"],"verbs":["list","get","watch"]},{"apiGroups":["apiregistration.k8s.io"],"resources":["apiservices"],"verbs":["list","get","watch"]},{"apiGroups":["apps"],"resources":["controllerrevisions"],"verbs":["list","get","watch"]},{"apiGroups":["node.k8s.io"],"resources":["runtimeclasses"],"verbs":["list","get","watch"]},{"apiGroups":["policy"],"resources":["poddisruptionbudgets","podsecuritypolicies"],"verbs":["list","get","watch"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["rolebindings","roles"],"verbs":["list","get","watch","update","create","delete","patch"]},{"apiGroups":["storage.k8s.io"],"resources":["storageclasses","volumeattachments"],"verbs":["list","get","watch"]},{"apiGroups":["","batch","apps"],"resources":["namespaces","deployments","jobs","pods","pods/log","pods/exec","configmaps","pods/portforward","pods/attach","persistentvolumeclaims","services","secrets","endpoints","events","podtemplates","replicationcontrollers","daemonsets","replicasets","statefulsets","cronjobs"],"verbs":["list","get","watch","create","update","patch","delete"]},{"apiGroups":["events.k8s.io"],"resources":["events"],"verbs":["list","get","watch","create","update","patch","delete"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["list","get","watch","create","update","patch","delete"]},{"apiGroups":["networking.k8s.io"],"resources":["ingresses"],"verbs":["list","get","watch","create","update","patch","delete"]},{"apiGroups":["networking.k8s.io"],"resources":["ingressclasses","networkpolicies"],"verbs":["list","get","watch"]}]}
  creationTimestamp: "2022-05-09T14:40:26Z"
  name: gitlab-sa-1228-ns-admin
  resourceVersion: "52878744"
  uid: 596ce22d-b867-4828-92d6-fcacbdafc203
rules:
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - limitranges
  verbs:
  - list
  - get
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - storageclasses
  - persistentvolumes
  - nodes
  - componentstatuses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - list
  - get
  - watch
  - update
  - create
  - delete
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  - batch
  - apps
  resources:
  - namespaces
  - deployments
  - jobs
  - pods
  - pods/log
  - pods/exec
  - configmaps
  - pods/portforward
  - pods/attach
  - persistentvolumeclaims
  - services
  - secrets
  - endpoints
  - events
  - podtemplates
  - replicationcontrollers
  - daemonsets
  - replicasets
  - statefulsets
  - cronjobs
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - get
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - networkpolicies
  verbs:
  - list
  - get
  - watch
