minikube: false
global:
  labels:
    app: skampi

# Common products
ska-tango-base:
  vnc:
    enabled: true
ska-sdp:
  enabled: false
ska-oso-scripting:
  enabled: false
ska-webjive:
  enabled: false
ska-ser-skuid:
  enabled: false
ska-tango-archiver:
  enabled: false
ska-landingpage:
  enabled: true

# Mid specific products
ska-mid-cbf:
  enabled: false
ska-csp-lmc-mid:
  enabled: false
ska-tmc-mid:
  enabled: false

# Low specific products
ska-tmc-low:
  enabled: false
ska-low-mccs:
  enabled: false
