elastic:
  enabled: false
fluentd:
  enabled: true
  remote: true
  elastic_host: 192.168.93.94
kibana:
  enabled: false
tests:
  enabled: true
hdbppdb:
  enabled: true
archiver:
  enabled: true

minikube: false