import os
import subprocess
from collections import namedtuple

import pytest
from kubernetes import client as k8s_client
from kubernetes import config as k8s_config

from tests.testsupport.helm import HelmTestAdaptor

DEFAULT_USE_TILLER_FLAG = False
DEFAULT_TEST_NAMESPACE = "ci"


def pytest_addoption(parser):
    parser.addoption(
        "--use-tiller-plugin", action="store_true", default=False, help="Wraps helm commands in `helm tiller run --`."
    )
    parser.addoption(
        "--test-namespace", action="store", default=DEFAULT_TEST_NAMESPACE,
        help="The namespace to run infrastructure tests in. Default is 'ci', but should be autogenerated in pipeline based on $CI_JOB_ID"
    )


@pytest.fixture(scope="session")
def test_namespace(pytestconfig):
    return pytestconfig.getoption("--test-namespace")


@pytest.fixture(scope="session")
def infratests_context(pytestconfig, test_namespace):
    InfraTestContext = namedtuple('InfraTestContext', ['helm_adaptor'])

    # collect options
    use_tiller_plugin = pytestconfig.getoption("--use-tiller-plugin")
    markers = pytestconfig.getoption("-m")

    # no need to manage a cluster if no deployment tests are included
    if len(markers) != 0 and "chart_deploy" not in markers:
        yield InfraTestContext(HelmTestAdaptor(use_tiller_plugin, test_namespace))
    else:
        # idempotently create test namespace
        get_ns_cmd = "kubectl get namespaces {}".format(test_namespace)
        get_ns_result = subprocess.run(get_ns_cmd.split(), stdout=subprocess.PIPE, shell=True)

        if (get_ns_result.returncode != 0):
            # create test namespace
            create_ns_cmd = "kubectl create namespace {}".format(test_namespace)
            create_ns_result = subprocess.run(create_ns_cmd.split(), stdout=subprocess.PIPE, encoding="utf8",
                                              check=True)

        # build and yield infratestcontext fixture object
        helm_adaptor = HelmTestAdaptor(use_tiller_plugin, test_namespace)
        infratestcontext = InfraTestContext(helm_adaptor)
        yield infratestcontext

        # teardown context (delete namespace)
        delete_ns_cmd = "kubectl delete namespace {}".format(test_namespace)
        subprocess.run(delete_ns_cmd.split(), stdout=subprocess.PIPE, encoding="utf8", check=True)


@pytest.fixture(scope="session")
def helm_adaptor(infratests_context):
    return infratests_context.helm_adaptor


@pytest.fixture(scope="session")
def k8s_api():
    k8s_config.load_kube_config()
    return k8s_client
