display: ":0"
xauthority: "~/.Xauthority"

global:
  retry:
    - "--sleep=1"
    - "--tries=100"
  sub-system:
    ska-tango-util:
      enabled: false
    ska-tango-base:
      enabled: false
    webjive:
      enabled: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    timeout: 300s
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.5
      pullPolicy: IfNotPresent

landingpage:
  enabled: true
  MVPInstance: mvp-mid

skuid:
  enabled: true
  skuid:
    use_pv: false
    config:
      generator_id: mvp01

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: false

webjive:
  enabled: true
  minikube: false
  ingress:
    enabled: true
    nginx: true
    hostname: k8s.stfc.skao.int
  tangogql:
    replicas: 3
    resources:
      requests:
        cpu: 600m # 600m = 0.6 CPU
        memory: 512Mi # 512Mi = 0.5 GB mem
      limits:
        cpu: 1000m # 1000m = 1 CPU
        memory: 1024Mi # 1024Mi = 1 GB mem

oet-scripts.enabled:
  enabled: true
  ingress:
    hostname: k8s.stfc.skao.int
  system: TM-mid
  telescope: SKA-mid
  central_node: ska_mid/tm_central/central_node
  subarray: ska_mid/tm_subarray_node
  jupyter:
    featureFlags:
      readViaPubSub: true
  rest:
    featureFlags:
      readViaPubSub: true

#telescope control
## mid-cbf
ska-mid-cbf:
  enabled: true

## mid-csp
ska-csp-lmc-mid:
  enabled: true

## sdp
sdp:
  enabled: true
  lmc:
    prefix: mid
    nsubarray: 3
  tango-base:
    enabled: false

## tm
ska-tmc-mid:
  enabled: true

ska-archiver:
  enabled: false
  dbname: default_mvp_archiver_db
