---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - default:
        memory: 256Mi
        cpu: 400m
        ephemeral-storage: 256Mi
      defaultRequest:
        memory: 64Mi
        cpu: 200m
        ephemeral-storage: 256Mi
      type: Container
