{{ $localchart := . }}

{{ template "ska-tango-util.configuration.tpl" . }}

{{ range $key, $deviceserver := .Values.deviceServers }}

{{ range $instance := $deviceserver.instances }}

{{ $context := dict "deviceserver" $deviceserver "image" $localchart.Values.mccs.image "local" $localchart "instance" $instance }}
{{ template "ska-tango-util.deviceserver.tpl" $context }}

{{ end }} ## instances

{{ end }} # deviceservers
