# This is a minimal deployment that is required to test the
# tango infrastructure and basic deployment of resources only
# Use by running
# make install-chart VALUES=resources/deployment_configurations/mid_tango_infrastructure.yaml

minikube: true

ska-tango-base:
  vnc:
    enabled: false
ska-mid-cbf:
  enabled: false
ska-csp-lmc-mid:
  legacy_compatibility: true
  enabled: false
ska-sdp:
  legacy_compatibility: true
  enabled: false
ska-tmc-mid:
  legacy_compatibility: true
  enabled: false
ska-oso-scripting:
  enabled: false
ska-taranta:
  enabled: false
ska-ser-skuid:
  enabled: false
ska-landingpage:
  enabled: false
ska-tango-archiver:
  legacy_compatibility: true
  enabled: false
