replicaCount: 1

image:
  repository: gcr.io/heptio-images/gangway
  tag: v3.2.0
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

gangway:
  port: 8080
  clusterName: mycluster
  authorizeURL: "https://gitlab.com/oauth/authorize"
  tokenURL: "https://gitlab.com/oauth/token"
  audience: "https://gitlab.com/oauth/userinfo"
  scopes: ["api","read_user","read_repository","write_repository","read_registry","sudo","openid","profile","email"]
  redirectURL: "http://chart-example.local/gangway_callback"
  clientID: "417ea12283741e0d74b22778d2dd3f5d0dcee78828c6e9a8fd5e8589025b8d2f"
  clientSecret: "27a5830ca37bd1956b2a38d747a04ae9414f9f411af300493600acc7ebe6107f"
  usernameClaim: "sub"
  apiServerURL: "https://192.168.100.28:8443"

tls: {}

extraVolumes: []

extraVolumeMounts: []

livenessProbe:
  scheme: HTTP

readinessProbe:
  scheme: HTTP

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
  path: /
  hosts: {}
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
