{{ $fullname := .Chart.Name }}
{{ $port := 80 }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 8 }}
    spec:
      containers:
      - name: {{ $fullname }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: chartinfo
              mountPath: /usr/share/nginx/html/external/
      volumes:
      - name: html
        configMap:
          name: {{ $fullname}}-html
      - name: chartinfo
        configMap:
          name: {{ .Values.chartInfoSource }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-html
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
data: 
  index.html: |-
{{ ($.Files.Get "data/index.html") | indent 4  }}
  scripts.js: |-
{{ ($.Files.Get "data/scripts.js") | indent 4  }}
  env.js: |-
    const MVP = '{{ .Values.MVPInstance }}';
    const NAMESPACE = '{{ .Release.Namespace }}';
    const temp = '{{ .Values.temp }}'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
spec:
  ports:
  - name: http
    port: {{ $port }}
    targetPort: {{ $port }}
  selector:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Namespace }}/start/(.*)
        backend:
          service:
            name: {{ $fullname }}
            port:
              number: {{ $port }}
        pathType: ImplementationSpecific
