{{- range $k, $v := .Values.storageVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $k }}
spec:
  storageClassName: nfss1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $v.size }}
{{- end }}












