# Default values for csp-proto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

midcbfmcs:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mid-cbf-mcs
    tag: 0.4.1-7ec0bbf
    pullPolicy: IfNotPresent

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.2.5.1
    pullPolicy: IfNotPresent

deviceServers:
  - name: cbfmaster
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/fsp/01 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/fsp/02 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/fsp/03 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/fsp/04 &&\
            /venv/bin/python /app/tangods/CbfMaster/CbfMaster/CbfMaster.py master"
  - name: cbfsubarray01
    args:
      - -c
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
            /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-01"
  - name: cbfsubarray02
    args:
      - -c
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
            /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-02"
  - name: cbfsubarray03
    args:
      - -c
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
            /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-03"
  - name: vcc001
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-001"
  - name: vcc002
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-002"
  - name: vcc003
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-003"
  - name: vcc004
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-004"
  - name: vcc005
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-005"
  - name: vcc006
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-006"
  - name: vcc007
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-007"
  - name: vcc008
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-008"
  - name: vcc009
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-009"
  - name: vcc010
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-010"
  - name: vcc011
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-011"
  - name: vcc012
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-012"
  - name: vcc013
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-013"
  - name: vcc014
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-014"
  - name: vcc015
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-015"
  - name: vcc016
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-016"
  - name: vcc017
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-017"
  - name: vcc018
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-018"
  - name: vcc019
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-019"
  - name: vcc020
    args:
      - -c
      - "/venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-020"
  - name: fsp01
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/005 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/006 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/007 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/008 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/009 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/010 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/011 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/012 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/013 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/014 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/015 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/016 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/017 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/018 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/019 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/020 &&\
            /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-01"
  - name: fsp02
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/005 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/006 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/007 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/008 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/009 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/010 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/011 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/012 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/013 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/014 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/015 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/016 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/017 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/018 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/019 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/020 &&\
            /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-02"
  - name: fsp03
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/005 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/006 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/007 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/008 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/009 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/010 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/011 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/012 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/013 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/014 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/015 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/016 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/017 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/018 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/019 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/020 &&\
            /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-03"
  - name: fsp04
    args:
      - -c
      - "retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/005 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/006 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/007 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/008 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/009 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/010 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/011 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/012 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/013 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/014 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/015 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/016 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/017 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/018 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/019 &&\
            retry --max=10 -- tango_admin --ping-device mid_csp_cbf/vcc/020 &&\
            /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-04"

nodeSelector: {}

affinity: {}

tolerations: []
