image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  # which ref to use for includes:
  # check variable settings here https://gitlab.com/ska-telescope/sdi/ska-cicd-makefile/-/settings/ci_cd
  INCLUDE_REF: master
  TERRAFORM_VERSION: "1.3.6"
  TFLINT_VERSION: "0.43.0"

stages:
  - lint
  - build
  - test
  - pages


default:
  tags:
  - k8srunner

# Trigger downstream testing project
# UPSTREAM_MAKEFILE_COMMIT_SHA variable is used in ska-cicd-stencil repo to update the makefile repo submodule

trigger_stencil:
  stage: test
  trigger: ska-telescope/sdi/ska-cicd-stencil
  variables:
    UPSTREAM_MAKEFILE_COMMIT_SHA: $CI_COMMIT_SHA

lint:
  stage: lint
  image: alpine:3.12
  before_script:
    - apk update && apk add --no-cache make bash git
    - mkdir -p build/reports
    - make help Makefile
    - make long-help oci
    - make help-test-colours
  script:
  - "export TARGETS=$(make -p | grep '.PHONY' | grep -v -E '^#' | sed 's/.PHONY: //')"
  - export DATACENTRE=d ENVIRONMENT=e SERVICE=s TF_HTTP_USERNAME=u TF_HTTP_PASSWORD=p
  - 'tests=0; cd tests; for i in ${TARGETS}; do echo "Checking target: $i"; make -n $i >../build/$i.log 2>&1; tests=$((tests+1)); done; export tests'
  - export lines=$(cat Makefile | wc -l | awk '{print $1}')
  - echo '<?xml version="1.0" encoding="UTF-8"?><testsuites><testsuite errors="0" failures="0" name="customlint" skipped="0" tests="'${tests}'" time="0.000" timestamp="'`date +"%Y-%m-%dT%H:%M:%S"`'"></testsuite></testsuites>' > ../build/reports/linting.xml
  - echo '<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="wattle" name="customtest" skipped="0" tests="'${tests}'" time="1.0" timestamp="'`date +"%Y-%m-%dT%H:%M:%S"`'"></testsuite></testsuites>' > ../build/reports/unit-tests.xml
  - echo '<?xml version="1.0" ?><coverage branch-rate="0.0" branches-covered="1" branches-valid="1" complexity="0" line-rate="0.0" lines-covered="${lines}" lines-valid="${lines}" timestamp="'`date +"%s"`'" version="5.0.4"></coverage>' > ../build/reports/code-coverage.xml
  artifacts:
    when: always
    paths:
    - build

lint-with-gnu-alpine:
  extends: lint
  before_script:
    - apk update && apk add --no-cache make bash git gawk sed ncurses
    - mkdir -p build/reports
    - rm -rf /usr/bin/awk
    - ln -s /usr/bin/gawk /usr/bin/awk
    - make help Makefile
    - make long-help oci
    - make help-test-colours

lint-with-debian:
  extends: lint
  image: ubuntu:18.04
  before_script:
    - apt-get update
    - apt-get install -y make bash git gawk ncurses-term
    - mkdir -p build/reports
    - make help Makefile
    - make long-help oci
    - make help-test-colours

test:
  stage: test
  before_script:
    - apk update && apk add --no-cache make bash git curl openssl docker jq
    - pip3 install sphinx==5.1.1 sphinx-rtd-theme==1.0.0 recommonmark==0.7.1 conan
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - helm repo add ska https://artefact.skao.int/repository/helm-internal
    - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip
    - unzip terraform.zip && rm terraform.zip && mv terraform /usr/bin/terraform
    - wget https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip -O tflint.zip
    - unzip tflint.zip && rm tflint.zip && mv tflint /usr/bin/tflint
    - mkdir -p build/reports
    - mkdir -p build/charts
  script:
  - cd tests
  - make test
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

include:
  # Docs
  - project: 'ska-telescope/templates-repository'
    ref: $INCLUDE_REF
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

    # .post steps
  - project: 'ska-telescope/templates-repository'
    ref: $INCLUDE_REF
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'