minikube: false

# Common products
ska-tango-base:
  vnc:
    enabled: false
ska-sdp:
  enabled: true
ska-oso-scripting:
  enabled: true
ska-taranta:
  enabled: true
ska-ser-skuid:
  enabled: true
ska-tango-archiver:
  enabled: true
ska-landingpage:
  enabled: true

# Mid specific products
ska-mid-cbf:
  enabled: true
ska-csp-lmc-mid:
  legacy_compatibility: true
  enabled: true
ska-tmc-mid:
  legacy_compatibility: true
  enabled: true
ska-dish-lmc:
  legacy_compatibility: true
  enabled: false