{{ if .Values.itango.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
    chart: {{ template "oet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 22
      nodePort: {{ .Values.itango.nodePort }}
  selector:
    app: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: itango-configmap-{{ template "oet.name" .}}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  environment: |
    TANGO_HOST=databaseds-tango-base-{{ .Release.Name }}:10000
    PATH=/venv/bin:$PATH
  profile: |
    cd /app
    /venv/bin/itango3 --profile=ska
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
    chart: {{ template "oet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
  serviceName: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: itango-{{ template "oet.name" . }}-{{ .Release.Name }}
        chart: {{ template "oet.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Always
      initContainers:
      - name: check-databaseds-ready
        image: "{{ .Values.rest.image.registry }}/{{ .Values.rest.image.image }}:{{ .Values.rest.image.tag }}"
        command:
          - /usr/local/bin/wait-for-it.sh
          - databaseds-tango-base-{{ .Release.Name }}:10000
          - --timeout=30
          - --strict
          - --
          - echo databaseds ready
      containers:
      - name: oet-itango
        image: "{{ .Values.itango.image.registry }}/{{ .Values.itango.image.image }}:{{ .Values.itango.image.tag }}"
        imagePullPolicy: {{ .Values.itango.image.pullPolicy }}
        ports:
          - name: oet-itango
            containerPort: 22
        volumeMounts:
          - name: itango-configmap-volume
            mountPath: /home/tango/.profile
            subPath: .profile
          - name: itango-configmap-volume
            mountPath: /etc/environment
            subPath: environment
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: {{ .Values.itango.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.itango.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.itango.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.itango.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.itango.readinessProbe.failureThreshold }}
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: {{ .Values.itango.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.itango.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.itango.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.itango.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.itango.livenessProbe.failureThreshold }}
      volumes:
        - name: itango-configmap-volume
          configMap:
            name: itango-configmap-{{ template "oet.name" .}}-{{ .Release.Name }}
            items:
            - key: profile
              path: .profile
            - key: environment
              path: environment
      resources:
  {{ toYaml .Values.itango.resources | indent 10 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{ end }}
