# template jobs
.mid_itf_base:
  tags:
    - ska-k8srunner-za-itf
  variables:
    CONFIG: mid
    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
    K8S_CHART: "$DEPLOYMENT_CONFIGURATION"
    MINIKUBE: false
    INGRESS_HOST: 10.164.0.10:30080
    CLUSTER_DOMAIN: za-itf.skao.int
    K8S_EXTRA_PARMS: '--set global.ska-tango-archiver.enabled=false  --set ska-tango-archiver.enabled=false'
  when: manual

.mid_itf_deploy:
  extends:
    - .deploy_chart_before
  script:
    - make skampi-links
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml

# on-demand deployment from branch to branch namespace
.mid_itf_branch_job:
  stage: on-demand
  extends:
    - .mid_itf_base
  variables:
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CONFIG"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    ARCHIVER_DBNAME: "$CI_JOB_ID-$CONFIG_archiver_db"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

mid_itf_on_demand_deploy:
  extends:
    - .mid_itf_branch_job
    - .mid_itf_deploy

mid_itf_on_demand_destroy:
  extends:
    - .mid_itf_branch_job
    - .uninstall_chart
  variables:
    KEEP_NAMESPACE: "true"

# on-demand from master to integration namespace
.mid_itf_integration_job:
  stage: deploy_integration
  extends:
    - .mid_itf_base
  variables:
    HELM_RELEASE: "integration-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "integration-$CONFIG"
    KUBE_NAMESPACE_SDP: "integration-$CONFIG-sdp"
    SERVICE_ACCOUNT: "ci-svc-integration-$CONFIG"
    ARCHIVER_DBNAME: "integration_$CONFIG_archiver_db"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

mid_itf_deploy_integration:
  extends:
    - .mid_itf_integration_job
    - .mid_itf_deploy

mid_itf_destroy_integration:
  extends:
    - .mid_itf_integration_job
    - .uninstall_chart
  variables:
    KEEP_NAMESPACE: "true"

# on-demand from tags to staging namespace
.mid_itf_staging_job:
  stage: deploy_staging
  extends:
    - .mid_itf_base
  variables:
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "staging-$CONFIG"
    KUBE_NAMESPACE_SDP: "staging-$CONFIG-sdp"
    SERVICE_ACCOUNT: "ci-svc-staging-$CONFIG"
    ARCHIVER_DBNAME: "staging_$CONFIG_archiver_db"
  only:
    - tags

mid_itf_deploy_staging:
  extends:
    - .mid_itf_staging_job
    - .mid_itf_deploy

mid_itf_destroy_staging:
  extends:
    - .mid_itf_staging_job
    - .uninstall_chart
  variables:
    KEEP_NAMESPACE: "true"
