# ################################################
# # SKA Low CI Stages
# ################################################

# Local Anchors
.tags_psi_low: &tags_psi_low
  - k8srunner-psi-low

.psi_test_template: &psi_test_definition
  script:
    - bash scripts/gitlab_section.sh vars "Make config dump" make vars
    - make install-or-upgrade || true
    - bash scripts/gitlab_section.sh kube_res "Kubernetes resources dump"
      kubectl get all,pv,pvc,ingress -n $KUBE_NAMESPACE
    - make k8s_test
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always

# Low specific job steps
# testing environment (low_)
low_uninstall:
  stage: clean
  extends:
      - .dry_run
      - .tags_default
  #  - .uninstall_definition
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "test-low"
    action: stop

low_deploy:
  stage: deploy
  extends:
    - .dry_run
    - .tags_default
  #- .deploy_definition
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
  environment:
    name: "test-low"
    on_stop: low_uninstall

# quarantine testing environment (low_quarantine)

.low_quarantine_deploy:
  stage: deploy
  extends:
    - .dry_run
    - .tags_default
  #  - .deploy_definition
  variables:
    HELM_RELEASE: "test-low-q"
    KUBE_NAMESPACE: "ci-quarantine-low"
    KUBE_NAMESPACE_SDP: "ci-quarantine-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
  environment:
    name: "low-quarantine"
    on_stop: low_quarantine_uninstall
  when: manual

.low_quarantine_uninstall:
  stage: cleanup
  extends:
    - .tags_default
    - .dry_run
  #  - .deploy_definition
  variables:
    HELM_RELEASE: "test-low-q"
    KUBE_NAMESPACE: "ci-quarantine-low"
    KUBE_NAMESPACE_SDP: "ci-quarantine-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "low-quarantine"
    action: stop
  when: manual

# psi-low-integration environment

psi_low_uninstall:
  stage: clean
  extends:
    - .dry_run
  #  - .uninstall_definition
  #tags: *tags_psi_low
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "psi-low-integration"
    action: stop
  allow_failure: true

psi_low_deploy:
  stage: deploy
  extends:
    - .dry_run
  #  - .deploy_definition
  #tags: *tags_psi_low
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "psi-low-integration"
    on_stop: psi_low_uninstall
  allow_failure: true

# low on demand environment

low_on_demand_uninstall:
  stage: clean
  extends:
    - .dry_run
    - .on_demand_definition
    - .tags_default
  #  - .uninstall_scripts
  variables:
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
  environment:
    name: "test-low/$CI_COMMIT_REF_NAME"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low
    action: stop

low_on_demand_deploy:
  stage: deploy
  extends:
    - .dry_run
    - .on_demand_definition
    - .tags_default
  #  - .deploy_scripts
  variables:
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
  environment:
    name: "test-low/$CI_COMMIT_REF_NAME"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low
    on_stop: low_on_demand_uninstall

psi_low_on_demand_uninstall:
  stage: cleanup
  extends:
    - .dry_run
  #  - .uninstall_scripts
  tags: *tags_psi_low
  variables:
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
  environment:
    name: "psi-low-test/$CI_COMMIT_REF_NAME"
    action: stop

psi_low_on_demand_deploy:
  stage: deploy
  extends:
    - .dry_run
    - .on_demand_definition
  #  - .deploy_scripts
  # tags: *tags_psi_low
  variables:
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
  environment:
    name: "psi-low-test/$CI_COMMIT_REF_NAME"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low
    on_stop: psi_low_on_demand_uninstall

low_test:
  retry: 2
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .test_definition
  #  - .xray_upload
  variables:
    MARK: "(skalow or common) and not quarantine"
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
    ARCHIVER_DBNAME: "integration_low_archiver_db"
  environment:
    name: "test-low"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    on_stop: low_uninstall
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $STRESS_TEST_DURATION && $STRESS_TEST_DURATION != ""'

low_test_quarantine:
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .test_definition
  #  - .xray_upload
  variables:
    MARK: "(skalow or common) and quarantine"
    HELM_RELEASE: "test-low-q"
    KUBE_NAMESPACE: "ci-quarantine-low"
    KUBE_NAMESPACE_SDP: "ci-quarantine-low-sdp"
    ARCHIVER_DBNAME: "integration_low_archiver_db"
    DELETE: "true"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "low-quarantine"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    on_stop: low_quarantine_uninstall
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $STRESS_TEST_DURATION != ""'
      allow_failure: true

psi_low_test:
  stage: test
  extends:
    - .dry_run
  #  - .xray_upload
  tags: *tags_psi_low
  variables:
    HELM_RELEASE: "test-low"
    KUBE_NAMESPACE: "integration-low"
    KUBE_NAMESPACE_SDP: "integration-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    MARK: "(skalow or common) and not archiver and not quarantine"
    KEEP_NAMESPACE: "true"
    ARCHIVER_DBNAME: "integration_low_archiver_db"
    INGRESS_HOST: "202.9.15.131" # psi-head ip
  <<: *psi_test_definition
  environment:
    name: "psi-low-integration"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: psi_low_uninstall
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $STRESS_TEST_DURATION != ""'

low_on_demand_test:
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .test_definition
  variables:
    DEPLOYMENT_CONFIGURATION: "ska-low"
    MARK: "skalow or common"
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-low_archiver_db"
  #before_script:
  # using reference as there seems to be a problem with extends
  #- !reference [.create_k8s_creds, before_script]
  environment:
    name: "test-low/$CI_COMMIT_REF_NAME"
    url: "http://$INGRESS_HOST/ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low
    on_stop: low_on_demand_uninstall
    auto_stop_in: 2 hours
  rules:
    - if: "$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $STRESS_TEST_DURATION"
      when: manual

psi_low_on_demand_test:
  stage: test
  #tags: *tags_psi_low
  extends:
    - .dry_run
  variables:
    DEPLOYMENT_CONFIGURATION: "ska-low"
    MARK: "(skalow or common) and not archiver"
    HELM_RELEASE: "test-low-$CI_COMMIT_BRANCH"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low-sdp"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-low_archiver_db"
    INGRESS_HOST: "202.9.15.131" # psi-head ip
  #before_script:
  # using reference as there seems to be a problem with extends
  #- !reference [.create_k8s_creds, before_script]
  #<<: *psi_test_definition
  environment:
    name: "psi-low-test/$CI_COMMIT_REF_NAME"
    url: "http://$INGRESS_HOST/ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-low/taranta"
    on_stop: psi_low_on_demand_uninstall
    auto_stop_in: 2 hours
  rules:
    - if: "$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
      when: manual

get_sizes_low:
  stage: debug
  extends:
    - .dry_run
  # - .tags_default
  variables:
    KUBE_NAMESPACE: "integration-low"
    KEEP_NAMESPACE: "true"
  script:
    - make get_size_images
  environment:
    name: "test-low"
  only:
    refs:
      - master

# staging environments

low_uninstall_staging:
  stage: clean_staging
  extends:
    - .dry_run
    - .tags_default
  #  - .uninstall_scripts
  variables:
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  rules:
    - if: '$CI_COMMIT_TAG && $DELETE == "true"'
  environment:
    name: "staging-low"
    action: stop

psi_low_uninstall_staging:
  stage: clean_staging
  extends:
    - .dry_run
  #  - .uninstall_scripts
  tags: *tags_psi_low
  variables:
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
  rules:
    - if: '$CI_COMMIT_TAG && $DELETE == "true"'
  environment:
    name: "psi-low-staging"
    action: stop

low_deploy_staging:
  stage: deploy_staging
  extends:
    - .dry_run
    - .tags_default
  #  - .deploy_definition
  variables:
    HELM_REPO_NAME: "skatelescope"
    UMBRELLA_CHART_PATH: "$HELM_REPO_NAME/mvp-low"
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    KEEP_NAMESPACE: "true"
  environment:
    name: "staging-low"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    on_stop: low_uninstall_staging
  rules:
    - if: "$CI_COMMIT_TAG"
  # needs:
  #   - job: low_uninstall_staging

psi_low_deploy_staging:
  stage: deploy_staging
  extends:
    - .dry_run
  #  - .deploy_definition
  tags: *tags_psi_low
  variables:
    HELM_REPO_NAME: "skatelescope"
    UMBRELLA_CHART_PATH: "$HELM_REPO_NAME/ska-low" ## The name of the chart as published to CAR
    HELM_RELEASE: "staging-low"
    KUBE_NAMESPACE: "staging-low"
    KUBE_NAMESPACE_SDP: "staging-low-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-low"
    INGRESS_HOST: "202.9.15.131" # psi-head ip
  environment:
    name: "psi-low-staging"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    on_stop: psi_low_uninstall_staging
  rules:
    - if: "$CI_COMMIT_TAG"
  # needs:
  #   - job: psi_low_uninstall_staging
