---
# ################################################
# # SKA Low CI Stages
# ################################################

# low merge blocking job - must pass for pipeline success
#low-test:
#  stage: test
#  variables:
#    CONFIG: low
#    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
#    K8S_CHART: "$DEPLOYMENT_CONFIGURATION"
#    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
#    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG"
#    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG-sdp"
#    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_JOB_ID"
#    ARCHIVER_DBNAME: "$CI_JOB_ID-$CONFIG_archiver_db"
#    DISABLE_MAINTAIN_ON: "True"
#    TEST_ENV: "BUILD_IN"
#    ATTR_SYNCH_ENABLED_GLOBALLY: "True"
#    COUNT: 1
#    EXIT_AT_FAIL: "false"
#    CAPTURE_LOGS: "True"
#    DEBUG_ENTRYPOINT: "True"
#    DEBUG_ENTRYPOINT_EXTENDED: "True"
#    LIVE_LOGGING_EXTENDED: "True"
#  extends:
#    - .tags_default
#  script:
#    - !reference [.deploy_chart_before, before_script]
#    - !reference [.test_deployment, script]
#  environment:
#    name: test/ska-$CONFIG-$CI_COMMIT_REF_SLUG
#    kubernetes:
#      # This repetition is needed for gitlab to parse the namespace correctly
#      namespace: $KUBE_NAMESPACE
#    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
#  artifacts:
#    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
#    paths:
#      - "build/"
#    reports:
#      junit: build/report.xml
#    when: always
#  retry: 1
#
#clean-low-test:
#  stage: clean_test_env
#  variables:
#    CONFIG: low
#    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
#    K8S_CHART: "$DEPLOYMENT_CONFIGURATION"
#    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
#    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG"
#    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG-sdp"
#    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_JOB_ID"
#    ARCHIVER_DBNAME: "$CI_JOB_ID-$CONFIG_archiver_db"
#    DISABLE_MAINTAIN_ON: "True"
#    TEST_ENV: "BUILD_OUT"
#    COUNT: 1
#    TEL: low
#  extends:
#    - .tags_default
#  script:
#    - !reference [.uninstall_chart_after, after_script]
#  when: always
#  environment:
#    name: test/ska-$CONFIG-$CI_COMMIT_REF_SLUG
#    kubernetes:
#      # This repetition is needed for gitlab to parse the namespace correctly
#      namespace: $KUBE_NAMESPACE
#  allow_failure: true

# Low on-demand deployment
low_on_demand_deploy:
  stage: build
  variables:
    CONFIG: low
    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
    K8S_CHART: "$DEPLOYMENT_CONFIGURATION"
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CONFIG"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CONFIG-sdp"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    ARCHIVER_DBNAME: "${CONFIG}_archiver_db"
  extends:
    - .tags_default
    - .set_dbname
    - .deploy_chart_before
  script:
    - make skampi-links
  environment:
    name: test/ska-$CONFIG-$CI_COMMIT_REF_SLUG
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
  when: manual
  allow_failure: true

# Low integration

.low-integration-config:
  variables:
    CONFIG: low
    DEPLOYMENT_CONFIGURATION: ska-$CONFIG
    K8S_CHART: $DEPLOYMENT_CONFIGURATION
    KUBE_NAMESPACE: integration-$CI_PROJECT_NAME-$CONFIG
    KUBE_NAMESPACE_SDP: integration-$CI_PROJECT_NAME-$CONFIG-sdp
    HELM_RELEASE: $CONFIG
    SERVICE_ACCOUNT: integration-$CONFIG-sa
    ARCHIVER_DBNAME: integration-$CONFIG-archiver_db
    INGRESS_HOST: k8s.stfc.skao.int
    KEEP_NAMESPACE: "true"
  environment:
    name: integration-$CI_PROJECT_NAME-$CONFIG

low-deploy-integration:
  extends:
    - deploy-integration
    - .low-integration-config
  variables:
    KUBE_NAMESPACE: integration-$CI_PROJECT_NAME-$CONFIG
  after_script:
    - make skampi-links
  environment:
    name: integration-$CI_PROJECT_NAME-$CONFIG
    on_stop: low-stop-integration
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG

low-info-integration:
  extends:
    - info-integration
    - .low-integration-config
  variables:
    KUBE_NAMESPACE: integration-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: integration-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual

low-stop-integration:
  extends:
    - stop-integration
    - .low-integration-config
  needs:
    - low-deploy-integration
  variables:
    KUBE_NAMESPACE: integration-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: integration-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual

low-redeploy-integration:
  extends:
    - redeploy-integration
    - .low-integration-config
  variables:
    KUBE_NAMESPACE: integration-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: integration-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual

# Low staging

.low-staging-config:
  variables:
    CONFIG: low
    DEPLOYMENT_CONFIGURATION: ska-$CONFIG
    K8S_CHART: $DEPLOYMENT_CONFIGURATION
    KUBE_NAMESPACE: staging-$CI_PROJECT_NAME-$CONFIG
    KUBE_NAMESPACE_SDP: staging-$CI_PROJECT_NAME-$CONFIG-sdp
    HELM_RELEASE: $CONFIG
    SERVICE_ACCOUNT: staging-$CONFIG-sa
    ARCHIVER_DBNAME: staging-$CONFIG-archiver_db
    INGRESS_HOST: k8s.stfc.skao.int
    KEEP_NAMESPACE: "true"
  environment:
    name: staging-$CI_PROJECT_NAME-$CONFIG

low-deploy-staging:
  extends:
    - deploy-staging
    - .low-staging-config
  needs:
    - low-deploy-integration
  variables:
    KUBE_NAMESPACE: staging-$CI_PROJECT_NAME-$CONFIG
  after_script:
    - make skampi-links
  environment:
    name: staging-$CI_PROJECT_NAME-$CONFIG
    on_stop: low-stop-staging
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG

low-info-staging:
  extends:
    - info-staging
    - .low-staging-config
  variables:
    KUBE_NAMESPACE: staging-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: staging-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual

low-stop-staging:
  extends:
    - stop-staging
    - .low-staging-config
  needs:
    - low-deploy-staging
  variables:
    KUBE_NAMESPACE: staging-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: staging-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual

low-redeploy-staging:
  extends:
    - redeploy-staging
    - .low-staging-config
  variables:
    KUBE_NAMESPACE: staging-$CI_PROJECT_NAME-$CONFIG
  environment:
    name: staging-$CI_PROJECT_NAME-$CONFIG
  rules:
    - when: manual # TODO: Remove this
    - if: $CI_COMMIT_TAG
      when: manual
