# ################################################
# # SKA Mid CI Stages
# ################################################

# Mid specific job steps
# # testing environment (mid_)
mid_uninstall:
  stage: clean
  extends:
    - .uninstall_definition
  #- .tags_default
  # - .uninstall_definition
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "test"
    action: stop

mid_deploy:
  stage: deploy
  extends:
    - .dry_run
  #- .tags_default
  # - .deploy_definition
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "test"
    action: stop

mid_cleanup:
  stage: cleanup
  extends:
    - .dry_run
  #- .tags_default
  # - .uninstall_definition
  variables:
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "test"
    action: stop

# quarantine testing environment (mid_quarantine)

mid_quarantine_uninstall:
  stage: cleanup
  extends:
    - .uninstall_definition
    - .tags_default
  #  - .uninstall_definition
  variables:
    HELM_RELEASE: "test-mid-q"
    KUBE_NAMESPACE: "ci-quarantine-mid"
    KUBE_NAMESPACE_SDP: "ci-quarantine-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "mid-quarantine"
    action: stop
  when: manual

mid_quarantine_deploy:
  stage: cleanup
  extends:
    - .dry_run
    - .tags_default
  #  - .deploy_definition
  variables:
    HELM_RELEASE: "test-mid-q"
    KUBE_NAMESPACE: "ci-quarantine-mid"
    KUBE_NAMESPACE_SDP: "ci-quarantine-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "mid-quarantine"
    action: stop
  when: manual

mid_quarantine_cleanup:
  stage: cleanup
  extends:
    - .uninstall_definition
    - .tags_default
  #  - .uninstall_definition
  variables:
    HELM_RELEASE: "test-mid-q"
    KUBE_NAMESPACE: "ci-quarantine-mid"
    KUBE_NAMESPACE_SDP: "ci-quarantine-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "mid-quarantine"
    action: stop
  when: manual

# mid on demand environment

mid_on_demand_clean:
  stage: clean
  extends:
    - .dry_run
    - .on_demand_definition
    - .tags_default
  #  - .uninstall_scripts
  variables:
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
  environment:
    name: "test/$CI_COMMIT_REF_NAME"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid
    action: stop

mid_on_demand_deploy:
  stage: cleanup
  extends:
    - .dry_run
    - .on_demand_definition
    - .tags_default
  #  - .deploy_scripts
  variables:
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
  environment:
    name: "test/$CI_COMMIT_REF_NAME"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid
    action: stop

mid_test:
  retry: 2
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .uninstall_definition
  #  - .xray_upload
  variables:
    MARK: "(skamid or common) and not quarantine"
    HELM_RELEASE: "test-mid"
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
    ARCHIVER_DBNAME: "integration_mid_archiver_db"
  environment:
    name: "test"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      namespace: $KUBE_NAMESPACE
    on_stop: mid_uninstall
  only:
    refs:
      - master
  except:
    variables:
      - $STRESS_TEST_DURATION

mid_test_quarantine:
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .uninstall_definition
  #  - .xray_upload
  variables:
    MARK: "(skamid or common) and quarantine"
    HELM_RELEASE: "test-mid-q"
    KUBE_NAMESPACE: "ci-quarantine-mid"
    KUBE_NAMESPACE_SDP: "ci-quarantine-mid-sdp"
    ARCHIVER_DBNAME: "integration_mid_archiver_db"
    DELETE: "true"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "mid-quarantine"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      namespace: $KUBE_NAMESPACE
    on_stop: mid_quarantine_uninstall
  only:
    refs:
      - master
  except:
    variables:
      - $STRESS_TEST_DURATION
  allow_failure: true

mid_on_demand_test:
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .uninstall_definition
  variables:
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    MARK: "skamid or common"
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid-sdp"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-mid_archiver_db"
  # after_script:
  #   - make links
  #before_script:
  # using reference as there seems to be a problem with extends
  #- !reference [.create_k8s_creds, before_script]
  environment:
    name: "test/$CI_COMMIT_REF_NAME"
    url: "http://$INGRESS_HOST/ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid
    on_stop: mid_on_demand_uninstall
    auto_stop_in: 2 hours
  when: manual
  only:
    refs:
      - branches
  except:
    refs:
      - master

mid_stress_test:
  stage: test
  extends:
    - .dry_run
    - .tags_default
  #  - .stress_test_definition
  variables:
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    MARK: "skamid or common"
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE_PREFIX: "stress-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid"
    SERVICE_ACCOUNT: "stress-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
    ARCHIVER_NAMESPACE: "stress-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid-archiver"
    DBNAME: "$CI_COMMIT_BRANCH-mid_archiver_db"
  environment:
    name: "stress-test"
    url: "http://$INGRESS_HOST/stress-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: stress-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-mid
  rules:
    - if: $STRESS_TEST_DURATION

get_sizes_mid:
  stage: debug
  extends:
    - .dry_run
    - .tags_default
  variables:
    KUBE_NAMESPACE: "integration-mid"
    KEEP_NAMESPACE: "true"
  script:
    - make get_size_images
  environment:
    name: "test"
  only:
    refs:
      - master

mid_sdp_config_dump:
  stage: debug
  extends:
    - .dry_run
    - .tags_default
  variables:
    KUBE_NAMESPACE: "integration-mid"
    KUBE_NAMESPACE_SDP: "integration-mid-sdp"
    KEEP_NAMESPACE: "true"
  script:
    - kubectl exec -n $KUBE_NAMESPACE sdp-console-0 -- sdpcfg ls values -R / > sdp.config.json
  artifacts:
    paths:
      - sdp.config.json
  environment:
    name: "test"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
  when: manual
  only:
    refs:
      - master

mid_clean_staging:
  stage: clean_staging
  extends:
    - .dry_run
    - .tags_default
  #  - .uninstall_scripts
  variables:
    HELM_RELEASE: "staging-mid"
    KUBE_NAMESPACE: "staging-mid"
    KUBE_NAMESPACE_SDP: "staging-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  only:
    refs:
      - tags
    variables:
      - $DELETE == "true"
  environment:
    name: "staging-mid"
    action: stop

mid_deploy_staging:
  stage: deploy_staging
  extends:
    - .dry_run
    - .tags_default
  #  - .deploy_definition
  variables:
    HELM_REPO_NAME: "skatelescope"
    UMBRELLA_CHART_PATH: "$HELM_REPO_NAME/ska-mid" ## The name of the chart as published to CAR
    HELM_RELEASE: "staging-mid"
    KUBE_NAMESPACE: "staging-mid"
    KUBE_NAMESPACE_SDP: "staging-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true"
  environment:
    name: "staging-mid"
    url: "http://$INGRESS_HOST/$KUBE_NAMESPACE/taranta"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
    on_stop: mid_clean_staging
  only:
    refs:
      - tags
  # needs:
  #   - job: mid_clean_staging
