# ################################################
# # SKA Mid CI Stages
# ################################################


.mid_on_demand_vars:
  extends:
    - .tags_default
  variables:
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-mid_archiver_db"


.mid_branch_vars:
  extends:
    - .tags_default
  variables:
    HELM_RELEASE: "test-mid-$CI_COMMIT_BRANCH"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid-sdp"
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    KEEP_NAMESPACE: "true" # to stop ns deletion before actual uninstall
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_COMMIT_BRANCH"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid_archiver_db"


# mid_branch_uninstall:
#   stage: clean
#   extends:
#     - .mid_branch_vars
#     - .uninstall_definition
#   environment:
#     name: "test/$CI_COMMIT_REF_NAME"
#     kubernetes:
#       # This repetition is needed for gitlab to parse the namespace correctly
#       namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid
#     # action: stop
#   only:
#     refs:
#       - branches
#   except:
#     refs:
#       - master

# mid_deploy_branch:
#   stage: deploy
#   extends:
#     - .mid_branch_vars
#     - .output_step_info
#     - .tags_default
#     - .deploy_definition
#   environment:
#     name: "test/$CI_COMMIT_REF_NAME"
#     kubernetes:
#       # This repetition is needed for gitlab to parse the namespace correctly
#       namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid
#     # on_stop: mid_branch_uninstall
#   only:
#     refs:
#       - branches
#   except:
#     refs:
#       - master


# mid merge blocking job - must pass for pipeline success
mid_deploy_test_destroy:
  stage: test
  variables:
    CONFIG: mid
    DEPLOYMENT_CONFIGURATION: "ska-mid"
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid-sdp"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_JOB_ID"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid_archiver_db"
  extends:
    - .tags_default
    - .deploy_test_destroy_definition
  environment:
    name: "test-$CONFIG-branch"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE

# mid_branch_test_uninstall:
#   stage: cleanup
#   # needs:
#   #   - mid_on_demand_deploy
#   extends:
#     - .mid_branch_vars
#     - .output_step_info
#     - .tags_default
#     - .uninstall_definition
#     # - .on_demand_definition # DEFINITION MUST BE ADDED LAST
#   environment:
#     name: "test/$CI_COMMIT_REF_NAME"
#     kubernetes:
#       # This repetition is needed for gitlab to parse the namespace correctly
#       namespace: ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid
#   only:
#     refs:
#       - branches
#   except:
#     refs:
#       - master
