# ################################################
# # SKA Mid CI Stages
# ################################################

# # mid merge blocking job - must pass for pipeline success
# mid_deploy_test_destroy:
#   stage: test
#   variables:
#     CONFIG: mid
#     DEPLOYMENT_CONFIGURATION: "ska-mid"
#     HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
#     KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid"
#     KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid-sdp"
#     TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_JOB_ID"
#     SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
#     ARCHIVER_DBNAME: "$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-mid_archiver_db"
#   extends:
#     - .tags_default
#     - .deploy_test_destroy_definition
#   environment:
#     name: "test-$CONFIG-branch"
#     kubernetes:
#       # This repetition is needed for gitlab to parse the namespace correctly
#       namespace: $KUBE_NAMESPACE
#   retry: 2
