# ################################################
# # SKA Mid CI Stages
# ################################################

.cn_test_definition:
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - bash scripts/gitlab_section.sh vars "Make config dump" make vars
    - make centralnode_test
    - echo "############## Build Output"
    - find ./build
    - echo "############## EXTRA MAKE VARS OUTPUT"
    - make vars
    - echo "#####################################"

# mid merge blocking job - must pass for pipeline success
mid_deploy_test_destroy:
  stage: test
  variables:
    CONFIG: mid
    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG-sdp"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_JOB_ID"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_JOB_ID"
    ARCHIVER_DBNAME: "$CI_JOB_ID-$CONFIG_archiver_db"
    MARK: "not infra"
  extends:
    - .tags_default
    - .deploy_test_destroy_definition
  environment:
    name: "test-$CONFIG-branch"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
  retry: 2

cn_mid_deploy_test_destroy:
  stage: test
  variables:
    CONFIG: mid
    DEPLOYMENT_CONFIGURATION: "ska-$CONFIG"
    HELM_RELEASE: "test-$CONFIG-$CI_JOB_ID"
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG"
    KUBE_NAMESPACE_SDP: "ci-$CI_PROJECT_NAME-$CI_JOB_ID-$CONFIG-sdp"
    TANGO_DATABASE_DS: "databaseds-tango-base-test-$CI_JOB_ID"
    SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_JOB_ID"
    ARCHIVER_DBNAME: "$CI_JOB_ID-$CONFIG_archiver_db"
    MARK: "not infra"
  extends:
    - .tags_default
    - .deploy_definition
    - .cn_test_definition
    - .uninstall_definition
  environment:
    name: "test-$CONFIG-cn-branch"
    kubernetes:
      # This repetition is needed for gitlab to parse the namespace correctly
      namespace: $KUBE_NAMESPACE
  retry: 2