.test:
  stage: test
  variables:  # These should be passed by the upstream pipeline or manually set
    KUBE_BRANCH: $CI_JOB_ID
    KUBE_NAMESPACE: integration-$CONFIG
    PYTEST_MARK: (csp_startup or sdp or eda)
    XRAY_UPLOAD_ENABLED: "true"
    TRIGGER_ID: none
    DATACENTRE: ""
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE - ska-${CONFIG}
    - bash scripts/gitlab_section.sh vars "Make config dump" make vars
    - bash scripts/gitlab_section.sh get-ns "Get namespace resources" make k8s-get
    - bash scripts/gitlab_section.sh wait-ns "Wait namespace resources" make k8s-wait
    - bash scripts/gitlab_section.sh get-ns-dp "Get SDP namespace resources" make k8s-get KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - bash scripts/gitlab_section.sh wait-ns-dp "Wait SDP namespace resources" make k8s-wait KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - make k8s-test-runner
    - find ./build
    # Exit based on the make-k8s-test-runner output which is writing in build/status file
    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
    - exit $(cat build/status)
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $SKAMPI_TESTS_TRIGGER == $TRIGGER_ID
      allow_failure: false
    - if: $CI_PIPELINE_SOURCE == "pipeline" && $SKAMPI_TESTS_TRIGGER != $TRIGGER_ID
      when: never
    - if: ($CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event") && $DATACENTRE == "ska-techops"
    - when: manual
      allow_failure: true

test-low:
  extends:
    - .test
  variables:
    CONFIG: low
    DATACENTRE: ska-techops
    TRIGGER_ID: test-low
  tags:
    - k8srunner

test-low-dp:
  extends:
    - .test
  variables:
    CONFIG: low
    DATACENTRE: ska-dp
    TRIGGER_ID: test-low-dp
  tags:
    - ska-k8srunner-dp

test-mid:
  extends:
    - .test
  variables:
    CONFIG: mid
    DATACENTRE: ska-techops
    TRIGGER_ID: test-mid
  tags:
    - k8srunner

test-mid-dp:
  extends:
    - .test
  variables:
    CONFIG: mid
    DATACENTRE: ska-dp
    TRIGGER_ID: test-mid-dp
  tags:
    - ska-k8srunner-dp

trigger-tests:
  stage: trigger
  variables:
    SKA_SKAMPI_TESTS_REF: $CI_COMMIT_REF_SLUG
  trigger:
    project: ska-telescope/ska-skampi-deployment
    branch: st-1662-setup-ska-skampi-deployment # TODO: Change to main
    strategy: depend
    forward:
      yaml_variables: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - when: on_success

# If the pipeline is being exectued as a downstream, do not lint
# or build

notebook-lint:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - notebooks/**/*

python-lint:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - pyproject.toml
        - setup.py

docs-build:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - exists:
        - docs/**/*
