.test:
  stage: test
  variables:  # These should be passed by the upstream pipeline or manually set
    KUBE_NAMESPACE: "default"
    KUBE_BRANCH: $CI_JOB_ID
    EXPOSE_All_DS: "true"
    PYTEST_MARK: (csp_startup or sdp or eda)
    KEEP_NAMESPACE: "true"
    XRAY_UPLOAD_ENABLED: "false" # TODO: Remove this
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE - ska-${CONFIG}
    - bash scripts/gitlab_section.sh vars "Make config dump" make vars
    - bash scripts/gitlab_section.sh get-ns "Get namespace resources" make k8s-get
    - bash scripts/gitlab_section.sh wait-ns "Wait namespace resources" make k8s-wait
    - bash scripts/gitlab_section.sh get-ns-dp "Get SDP namespace resources" make k8s-get KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - bash scripts/gitlab_section.sh wait-ns-dp "Wait SDP namespace resources" make k8s-wait KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - make k8s-test-runner
    - find ./build
    # Exit based on the make-k8s-test-runner output which is writing in build/status file
    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
    - exit $(cat build/status)
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "build/"
    reports:
      junit: build/report.xml
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - when: manual

test-low:
  extends:
    - .test
  variables:
    CONFIG: low
  tags:
    - k8srunner

test-low-dp:
  extends:
    - .test
  variables:
    CONFIG: low
  tags:
    - ska-k8srunner-dp

test-mid:
  extends:
    - .test
  variables:
    CONFIG: mid
  tags:
    - k8srunner

test-mid-dp:
  extends:
    - .test
  variables:
    CONFIG: mid
  tags:
    - ska-k8srunner-dp
